### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by bhuschle** [bhuschle/CS5153_FinalProject#1]
- [x] Questionnaire answered by 10 participants (grads: 20) with at least 20 questions (4.2.3 in book) 
- [x] Stakeholder Profiles (4.3.4 in book) 
- [x] Use Cases (4.3.3 in book) 
- [x] Requirements Documentation (4.4.2 in book) 
- [x] Project Management Documentation (4.4.3 in book)

**Comment by bhuschle** [comment]
Finished and submitted milestone 1
